/**
 * @cortex/fsm-compiler — State Machine Runtime Engine
 *
 * Generic state machine runtime.
 *
 * Type parameters:
 *   TState — State enum type (generated by compiler)
 *   TEvent — Event enum type (generated by compiler)
 *   TContext — User-defined context carried through transitions
 */
// ────────────────────────────────────────────────────────────
// Errors
// ────────────────────────────────────────────────────────────
export class TransitionError extends Error {
    from;
    event;
    cause;
    constructor(message, from, event, cause) {
        super(message);
        this.from = from;
        this.event = event;
        this.cause = cause;
        this.name = "TransitionError";
    }
}
export class GuardError extends Error {
    guardName;
    cause;
    constructor(message, guardName, cause) {
        super(message);
        this.guardName = guardName;
        this.cause = cause;
        this.name = "GuardError";
    }
}
// ────────────────────────────────────────────────────────────
// State Machine
// ────────────────────────────────────────────────────────────
export class StateMachine {
    _current;
    _history;
    _transitionTable;
    _guards;
    _actions;
    _machineId;
    _version;
    _initialState;
    _finalStates;
    _transitionIdCounter = 0;
    _onAsyncActionError;
    constructor(definition, initialState, options = {}) {
        this._machineId = definition.id;
        this._version = definition.version;
        this._initialState = initialState;
        this._finalStates = new Set(definition.finalStates);
        this._current = initialState;
        this._history = [];
        this._guards = options.guards;
        this._actions = options.actions;
        this._onAsyncActionError = options.onAsyncActionError ?? (() => { });
        if (options.transitionTable) {
            this._transitionTable = options.transitionTable;
        }
        else {
            this._transitionTable = this._buildTransitionTable(definition);
        }
    }
    /** Current state (read-only outside) */
    get current() {
        return this._current;
    }
    /** Read-only history */
    get history() {
        return this._history;
    }
    get machineId() {
        return this._machineId;
    }
    get version() {
        return this._version;
    }
    /**
     * Check if event can be dispatched (guard evaluation).
     * Does not mutate state.
     */
    can(event, context) {
        const table = this._transitionTable[this._current];
        if (!table?.[event]) {
            return false;
        }
        const entry = table[event];
        if (entry.guard && this._guards) {
            try {
                return this._guards.evaluate(entry.guard, context);
            }
            catch {
                return false;
            }
        }
        return true;
    }
    /**
     * Dispatch an event.
     *
     * 1. Look up transition: current × event → (target, guard?, action?)
     * 2. Evaluate guard (if any) → reject if false
     * 3. Execute transition action (if any)
     * 4. Set current state
     * 5. Record in history
     *
     * @throws TransitionError if invalid or guard fails
     * @returns The new state
     */
    dispatch(event, context) {
        const table = this._transitionTable[this._current];
        if (!table?.[event]) {
            throw new TransitionError(`Invalid transition: ${String(this._current)} -> ${String(event)}`, this._current, event);
        }
        const entry = table[event];
        // Evaluate guard
        if (entry.guard && this._guards) {
            try {
                const allowed = this._guards.evaluate(entry.guard, context);
                if (!allowed) {
                    throw new TransitionError(`Guard "${entry.guard}" rejected transition: ${String(this._current)} -> ${String(event)} -> ${String(entry.target)}`, this._current, event);
                }
            }
            catch (e) {
                if (e instanceof TransitionError)
                    throw e;
                throw new GuardError(`Guard "${entry.guard}" threw an error`, entry.guard, e instanceof Error ? e : undefined);
            }
        }
        // Execute action
        if (entry.action && this._actions) {
            try {
                const result = this._actions.execute(entry.action, context);
                if (result instanceof Promise) {
                    // Note: In synchronous dispatch, we fire-and-forget async actions.
                    // For proper async handling, use dispatchAsync().
                    result.catch((err) => {
                        const actionName = entry.action;
                        this._onAsyncActionError(actionName, err);
                    });
                }
            }
            catch (e) {
                throw new Error(`Action "${entry.action}" threw: ${e instanceof Error ? e.message : String(e)}`, { cause: e });
            }
        }
        // Record transition
        const record = {
            timestamp: Date.now(),
            from: this._current,
            to: entry.target,
            event,
            context,
            id: `${this._machineId}-${++this._transitionIdCounter}-${Date.now()}`,
        };
        this._history.push(record);
        // Update state
        this._current = entry.target;
        return this._current;
    }
    /**
     * Reset machine to initial state (with optional history clear).
     */
    reset(clearHistory = true) {
        this._current = this._initialState;
        if (clearHistory) {
            this._history = [];
        }
    }
    /**
     * Check if machine is in a terminal (final) state.
     */
    get isFinal() {
        return this._finalStates.has(this._current);
    }
    /**
     * Serialize machine state for persistence.
     */
    serialize() {
        return {
            machineId: this._machineId,
            version: this._version,
            currentState: this._current,
            history: [...this._history],
            createdAt: Date.now(),
        };
    }
    /**
     * Restore machine from serialized snapshot.
     */
    static deserialize(snapshot, definition, options = {}) {
        const machine = new StateMachine({ ...definition, version: snapshot.version }, snapshot.currentState, options);
        machine._history = snapshot.history;
        machine._transitionIdCounter = snapshot.history.length;
        return machine;
    }
    // ── Private ──
    _buildTransitionTable(definition) {
        const table = {};
        for (const transition of definition.transitions) {
            const from = transition.from;
            const event = transition.event;
            if (!table[from]) {
                table[from] = {};
            }
            const curTable = table[from];
            curTable[event] = {
                target: transition.to,
                guard: transition.guard,
                action: transition.action,
            };
        }
        return table;
    }
}
//# sourceMappingURL=state-machine.js.map