/**
 * @cortex/fsm-compiler — State Machine Runtime Engine
 *
 * Generic state machine runtime.
 *
 * Type parameters:
 *   TState — State enum type (generated by compiler)
 *   TEvent — Event enum type (generated by compiler)
 *   TContext — User-defined context carried through transitions
 */

import type { FsmDefinition } from "../dsl/schema.js";
import type { GuardRegistry } from "./guard-registry.js";
import type { ActionRegistry } from "./action-registry.js";

// ────────────────────────────────────────────────────────────
// Transition Record
// ────────────────────────────────────────────────────────────

export interface TransitionRecord<TState extends string = string, TEvent extends string = string, TContext = unknown> {
  timestamp: number;
  from: TState;
  to: TState;
  event: TEvent;
  context?: TContext;
  /** Unique ID for this transition (for audit trail) */
  id: string;
  /** Optional cause — who/what triggered it */
  cause?: string;
}

// ────────────────────────────────────────────────────────────
// Machine Snapshot
// ────────────────────────────────────────────────────────────

export interface MachineSnapshot<TState extends string = string, TContext = unknown> {
  machineId: string;
  version: string;
  currentState: TState;
  history: TransitionRecord<TState, string, TContext>[];
  createdAt: number;
}

// ────────────────────────────────────────────────────────────
// Transition Table Entry
// ────────────────────────────────────────────────────────────

export interface TransitionEntry<TState extends string> {
  target: TState;
  guard?: string;
  action?: string;
}

export interface TransitionTable<TState extends string, _TEvent extends string> {
  [state: string]: {
    [event: string]: TransitionEntry<TState> | undefined;
  } | undefined;
}

// ────────────────────────────────────────────────────────────
// Options
// ────────────────────────────────────────────────────────────

export interface StateMachineOptions<TState extends string, TEvent extends string, _TContext = unknown> {
  guards?: GuardRegistry;
  actions?: ActionRegistry;
  /** Custom transition table (overrides generated one) */
  transitionTable?: TransitionTable<TState, TEvent>;
  /** Callback invoked when an async action fails (fire-and-forget path). Defaults to no-op. */
  onAsyncActionError?: (actionName: string, error: unknown) => void;
}

// ────────────────────────────────────────────────────────────
// Errors
// ────────────────────────────────────────────────────────────

export class TransitionError extends Error {
  constructor(
    message: string,
    public readonly from: string,
    public readonly event: string,
    public readonly cause?: Error,
  ) {
    super(message);
    this.name = "TransitionError";
  }
}

export class GuardError extends Error {
  constructor(
    message: string,
    public readonly guardName: string,
    public readonly cause?: Error,
  ) {
    super(message);
    this.name = "GuardError";
  }
}

// ────────────────────────────────────────────────────────────
// State Machine
// ────────────────────────────────────────────────────────────

export class StateMachine<TState extends string, TEvent extends string, TContext = void> {
  private _current: TState;
  private _history: TransitionRecord<TState, TEvent, TContext>[];
  private _transitionTable: TransitionTable<TState, TEvent>;
  private _guards?: GuardRegistry;
  private _actions?: ActionRegistry;
  private _machineId: string;
  private _version: string;
  private _initialState: TState;
  private _finalStates: Set<TState>;
  private _transitionIdCounter = 0;
  private _onAsyncActionError: (actionName: string, error: unknown) => void;

  constructor(
    definition: FsmDefinition,
    initialState: TState,
    options: StateMachineOptions<TState, TEvent, TContext> = {},
  ) {
    this._machineId = definition.id;
    this._version = definition.version;
    this._initialState = initialState;
    this._finalStates = new Set(definition.finalStates as TState[]);
    this._current = initialState;
    this._history = [];
    this._guards = options.guards;
    this._actions = options.actions;
    this._onAsyncActionError = options.onAsyncActionError ?? (() => {});

    if (options.transitionTable) {
      this._transitionTable = options.transitionTable;
    } else {
      this._transitionTable = this._buildTransitionTable(definition);
    }
  }

  /** Current state (read-only outside) */
  get current(): TState {
    return this._current;
  }

  /** Read-only history */
  get history(): readonly TransitionRecord<TState, TEvent, TContext>[] {
    return this._history;
  }

  get machineId(): string {
    return this._machineId;
  }

  get version(): string {
    return this._version;
  }

  /**
   * Check if event can be dispatched (guard evaluation).
   * Does not mutate state.
   */
  can(event: TEvent, context?: TContext): boolean {
    const table = this._transitionTable[this._current];
    if (!table?.[event]) {
      return false;
    }

    const entry = table[event];
    if (entry.guard && this._guards) {
      try {
        return this._guards.evaluate(entry.guard, context);
      } catch {
        return false;
      }
    }

    return true;
  }

  /**
   * Dispatch an event.
   *
   * 1. Look up transition: current × event → (target, guard?, action?)
   * 2. Evaluate guard (if any) → reject if false
   * 3. Execute transition action (if any)
   * 4. Set current state
   * 5. Record in history
   *
   * @throws TransitionError if invalid or guard fails
   * @returns The new state
   */
  dispatch(event: TEvent, context?: TContext): TState {
    const table = this._transitionTable[this._current];
    if (!table?.[event]) {
      throw new TransitionError(
        `Invalid transition: ${String(this._current)} -> ${String(event)}`,
        this._current,
        event,
      );
    }

    const entry = table[event];

    // Evaluate guard
    if (entry.guard && this._guards) {
      try {
        const allowed = this._guards.evaluate(entry.guard, context);
        if (!allowed) {
          throw new TransitionError(
            `Guard "${entry.guard}" rejected transition: ${String(this._current)} -> ${String(event)} -> ${String(entry.target)}`,
            this._current,
            event,
          );
        }
      } catch (e) {
        if (e instanceof TransitionError) throw e;
        throw new GuardError(
          `Guard "${entry.guard}" threw an error`,
          entry.guard,
          e instanceof Error ? e : undefined,
        );
      }
    }

    // Execute action
    if (entry.action && this._actions) {
      try {
        const result = this._actions.execute(entry.action, context);
        if (result instanceof Promise) {
          // Note: In synchronous dispatch, we fire-and-forget async actions.
          // For proper async handling, use dispatchAsync().
          result.catch((err) => {
            const actionName = entry.action as string;
            this._onAsyncActionError(actionName, err);
          });
        }
      } catch (e) {
        throw new Error(
          `Action "${entry.action}" threw: ${e instanceof Error ? e.message : String(e)}`,
          { cause: e },
        );
      }
    }

    // Record transition
    const record: TransitionRecord<TState, TEvent, TContext> = {
      timestamp: Date.now(),
      from: this._current,
      to: entry.target,
      event,
      context,
      id: `${this._machineId}-${++this._transitionIdCounter}-${Date.now()}`,
    };
    this._history.push(record);

    // Update state
    this._current = entry.target;
    return this._current;
  }

  /**
   * Reset machine to initial state (with optional history clear).
   */
  reset(clearHistory = true): void {
    this._current = this._initialState;
    if (clearHistory) {
      this._history = [];
    }
  }

  /**
   * Check if machine is in a terminal (final) state.
   */
  get isFinal(): boolean {
    return this._finalStates.has(this._current);
  }

  /**
   * Serialize machine state for persistence.
   */
  serialize(): MachineSnapshot<TState, TContext> {
    return {
      machineId: this._machineId,
      version: this._version,
      currentState: this._current,
      history: [...this._history],
      createdAt: Date.now(),
    };
  }

  /**
   * Restore machine from serialized snapshot.
   */
  static deserialize<TState extends string, TEvent extends string, TContext>(
    snapshot: MachineSnapshot<TState, TContext>,
    definition: FsmDefinition,
    options: StateMachineOptions<TState, TEvent, TContext> = {},
  ): StateMachine<TState, TEvent, TContext> {
    const machine = new StateMachine<TState, TEvent, TContext>(
      { ...definition, version: snapshot.version },
      snapshot.currentState,
      options,
    );
    machine._history = snapshot.history as TransitionRecord<TState, TEvent, TContext>[];
    machine._transitionIdCounter = snapshot.history.length;
    return machine;
  }

  // ── Private ──

  private _buildTransitionTable(definition: FsmDefinition): TransitionTable<TState, TEvent> {
    const table: TransitionTable<TState, TEvent> = {};

    for (const transition of definition.transitions) {
      const from = transition.from as TState;
      const event = transition.event as TEvent;

      if (!table[from]) {
        table[from] = {};
      }

      const curTable = table[from];
      curTable[event] = {
        target: transition.to as TState,
        guard: transition.guard,
        action: transition.action,
      };
    }

    return table;
  }
}
