/**
 * @cortex/fsm-compiler — State Machine Runtime Engine
 *
 * Generic state machine runtime.
 *
 * Type parameters:
 *   TState — State enum type (generated by compiler)
 *   TEvent — Event enum type (generated by compiler)
 *   TContext — User-defined context carried through transitions
 */
import type { FsmDefinition } from "../dsl/schema.js";
import type { GuardRegistry } from "./guard-registry.js";
import type { ActionRegistry } from "./action-registry.js";
export interface TransitionRecord<TState extends string = string, TEvent extends string = string, TContext = unknown> {
    timestamp: number;
    from: TState;
    to: TState;
    event: TEvent;
    context?: TContext;
    /** Unique ID for this transition (for audit trail) */
    id: string;
    /** Optional cause — who/what triggered it */
    cause?: string;
}
export interface MachineSnapshot<TState extends string = string, TContext = unknown> {
    machineId: string;
    version: string;
    currentState: TState;
    history: TransitionRecord<TState, string, TContext>[];
    createdAt: number;
}
export interface TransitionEntry<TState extends string> {
    target: TState;
    guard?: string;
    action?: string;
}
export interface TransitionTable<TState extends string, _TEvent extends string> {
    [state: string]: {
        [event: string]: TransitionEntry<TState> | undefined;
    } | undefined;
}
export interface StateMachineOptions<TState extends string, TEvent extends string, _TContext = unknown> {
    guards?: GuardRegistry;
    actions?: ActionRegistry;
    /** Custom transition table (overrides generated one) */
    transitionTable?: TransitionTable<TState, TEvent>;
    /** Callback invoked when an async action fails (fire-and-forget path). Defaults to no-op. */
    onAsyncActionError?: (actionName: string, error: unknown) => void;
}
export declare class TransitionError extends Error {
    readonly from: string;
    readonly event: string;
    readonly cause?: Error | undefined;
    constructor(message: string, from: string, event: string, cause?: Error | undefined);
}
export declare class GuardError extends Error {
    readonly guardName: string;
    readonly cause?: Error | undefined;
    constructor(message: string, guardName: string, cause?: Error | undefined);
}
export declare class StateMachine<TState extends string, TEvent extends string, TContext = void> {
    private _current;
    private _history;
    private _transitionTable;
    private _guards?;
    private _actions?;
    private _machineId;
    private _version;
    private _initialState;
    private _finalStates;
    private _transitionIdCounter;
    private _onAsyncActionError;
    constructor(definition: FsmDefinition, initialState: TState, options?: StateMachineOptions<TState, TEvent, TContext>);
    /** Current state (read-only outside) */
    get current(): TState;
    /** Read-only history */
    get history(): readonly TransitionRecord<TState, TEvent, TContext>[];
    get machineId(): string;
    get version(): string;
    /**
     * Check if event can be dispatched (guard evaluation).
     * Does not mutate state.
     */
    can(event: TEvent, context?: TContext): boolean;
    /**
     * Dispatch an event.
     *
     * 1. Look up transition: current × event → (target, guard?, action?)
     * 2. Evaluate guard (if any) → reject if false
     * 3. Execute transition action (if any)
     * 4. Set current state
     * 5. Record in history
     *
     * @throws TransitionError if invalid or guard fails
     * @returns The new state
     */
    dispatch(event: TEvent, context?: TContext): TState;
    /**
     * Reset machine to initial state (with optional history clear).
     */
    reset(clearHistory?: boolean): void;
    /**
     * Check if machine is in a terminal (final) state.
     */
    get isFinal(): boolean;
    /**
     * Serialize machine state for persistence.
     */
    serialize(): MachineSnapshot<TState, TContext>;
    /**
     * Restore machine from serialized snapshot.
     */
    static deserialize<TState extends string, TEvent extends string, TContext>(snapshot: MachineSnapshot<TState, TContext>, definition: FsmDefinition, options?: StateMachineOptions<TState, TEvent, TContext>): StateMachine<TState, TEvent, TContext>;
    private _buildTransitionTable;
}
//# sourceMappingURL=state-machine.d.ts.map